Hw12 calendar
fevse/otus_hw pull request #12
Opened 2024-03-27 10:30 UTC by fevse

## Домашнее задание №12 «Заготовка сервиса Календарь»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Понятность и чистота кода (включая факт, что проект разбит
на пакеты по определенной логике) - до 2 баллов
- [ ] Реализовано конфигурирование сервиса - 1 балл
- [ ] Используется логгер и он настраивается из конфига - 1 балл
- [ ] Запускается простой HTTP-сервер, мидлвара удовлетворяет ТЗ - 1 балл
- [ ] Присутствуют юнит-тесты - 1 балл

Реализовано хранилище:
- [ ] in-memory - 1 балл
- [ ] sql + миграции - 2 балла

#### Зачёт от 7 баллов

2024-03-27 10:32 UTC, fevse commented
@agneum
Добрый вечер, домашнее задание сделал, можете проверить.

2024-03-28 14:55 UTC, agneum requested changes
Спасибо за вариант решения. Хорошая работа, 
Важно починить линтер, иначе нет возможности смержить PR
Возможно, проблема с устаревшей версией

2024-03-28 14:55 UTC, agneum commented on hw12_13_14_15_calendar/Makefile
> +	go test -v ./internal/storage/memory/
Почему тестируется только один пакет?

2024-03-28 14:55 UTC, agneum commented on hw12_13_14_15_calendar/cmd/calendar/config.go
> +	return
Рекомендую не использовать naked return, а возвращать значения явно. Это позволит избежать многих ошибок и улучшит читаемость кода

2024-03-28 14:55 UTC, agneum commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		panic(err)
Паниковать не стоит, лучше корректно обработать ошибку и остановить исполнение

2024-03-28 14:55 UTC, agneum commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	}
Будет здорово, если инициализацию стораджа вынести в отдельный пакет, чтобы иметь возможность её переиспользовать и упростить код в main

2024-03-28 14:55 UTC, agneum commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +		event.Date.Day() == date.Day() {
Для получения значений дня более эффективно будет использовать функцию https://pkg.go.dev/time#Time.Date

2024-03-28 14:55 UTC, agneum commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	return s.db.Close()
Если вызвать Close без вызова Connect для инициализации, будет паника

2024-03-28 14:55 UTC, agneum approved these changes

2024-03-30 16:48 UTC, fevse commented
@agneum
Вечер добрый, замечания поправил, но с линтером проблему не решил.
Локально выдает "import 'path' is not allowed from list 'Main' (depguard)" в каждом файле где есть импорт.

2024-04-03 14:20 UTC, agneum commented
> @agneum Вечер добрый, замечания поправил, но с линтером проблему не решил. Локально выдает "import 'path' is not allowed from list 'Main' (depguard)" в каждом файле где есть импорт.

@fevse 
Вероятно, версия линтера 1.50.1 не работает корректно с Go 1.22, который используется в CI


Предупреждение от depguard можно исправить конфигом:
[https://github.com/OpenPeeDeeP/depguard?tab=readme-ov-file#config](https://github.com/OpenPeeDeeP/depguard?tab=readme-ov-file#config)
[https://github.com/OpenPeeDeeP/depguard?tab=readme-ov-file#example-configs](https://github.com/OpenPeeDeeP/depguard?tab=readme-ov-file#example-configs)

2024-04-04 14:53 UTC, fevse commented
@agneum
Поправил как смог, вроде работает.

2024-04-08 18:18 UTC, merged