HW02 is complited
fevse/otus_hw pull request #2
Opened 2023-12-12 14:32 UTC by fevse

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-12-13 14:24 UTC, agneum requested changes
Спасибо за вариант решения. 
Хорошая работа. Есть возможность немного упростить решение: вместо обращения по индексам к текущему, следующему и предыдущему символам, можно рассматривать текущий символ, запоминая предыдущий и состояние записи

Не хватает новых юнит-тестов, можно добавить их, например, в файл `unpack_test.go`.

Итого: 5 баллов из 10. Возвращаю решение на доработку

2023-12-13 14:24 UTC, agneum commented on hw02_unpack_string/unpack.go
> +		return string(sr[0]), nil
Можно вернуть исходную строку `s` без дополнительных конвертаций

2023-12-13 14:24 UTC, agneum commented on hw02_unpack_string/unpack.go
> +		fmt.Fprint(&res, string(sr[0]))
У `strings.Builder` есть методы записи байтов, рун, строк. Рекомендую использовать их для добавления символов

2023-12-13 14:24 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	for i < len(sr)-1 {
Рекомендовал бы использовать цикл `range` вместо ручного управления переменной-счётчиком

2023-12-13 14:24 UTC, agneum commented on hw02_unpack_string/unpack.go
> +			n, _ := strconv.Atoi(string(sr[i]))
Возвращаемые ошибки следует обрабатывать

2023-12-13 19:36 UTC, fevse commented on hw02_unpack_string/unpack.go
> +			n, _ := strconv.Atoi(string(sr[i]))
Добрый вечер! Поправил замечания, добавил тесты (я добавил к уже имеющимся или нужно было отдельную функцию написать?). И подскажите что следует делать с ошибками, вроде той что возвращает strconv.Atoi?

2023-12-14 03:27 UTC, agneum approved these changes
Спасибо за тесты, выглядит хорошо
Итого: 9 баллов из 10. Принято

2023-12-14 03:27 UTC, agneum commented on hw02_unpack_string/unpack.go
> +		cr, pr = v, cr
Значение текущей руны доступно в переменной `v`, поэтому можно не создавать отдельную переменную для неё

2023-12-14 03:27 UTC, agneum commented on hw02_unpack_string/unpack.go
> +				fmt.Printf("Atoi error: %v\n", err)
Если в `n` невалидное значение, с ним не получится дальше работать и корректно использовать в качестве аргумента `strings.Repeat`

2023-12-14 03:27 UTC, agneum commented on hw02_unpack_string/unpack.go
> +			n, _ := strconv.Atoi(string(sr[i]))
Можно добавить тесты к уже имеющимся

Ошибки следует проверить и обработать в зависимости от их критичности. Например, в данном случае может быть несколько вариантов:
- полностью прекратить выполнение функции
- пропустить обработку текущего элемента и перейти к следующей итерации
- игнорировать ошибку, продолжить выполнение цикла

Выбрать следует тот сценарий, который лучшим образом соответствует логике работы программы

2023-12-14 12:19 UTC, fevse commented on hw02_unpack_string/unpack.go
> +		cr, pr = v, cr
Поменял на v, cr убрал

2023-12-14 12:19 UTC, fevse commented on hw02_unpack_string/unpack.go
> +				fmt.Printf("Atoi error: %v\n", err)
Сделал возврат пустой строки и ошибки

2023-12-14 13:23 UTC, merged